[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[dependencies]
api_types           = {path="../api_types"}
tracing = "0.1.40"
tracy-client = "0.18.4"
ash             = {version = "^0.38", features = ["linked"]}
